FROM node:16.13.0-alpine3.12

ENV NODE_VERSION 14.18.1

WORKDIR /home/node/real-sns-ex-facebook/backend/app
COPY --chown=node:node ./backend/app /home/node/real-sns-ex-facebook/backend/app/
RUN npm install

USER node
